{
 "title": "ArturoOlivaresMartosAPI",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mem Usada vs Disponible",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "Memoria Disponible" },
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "Memoria Empleada" }
   ]
  },
  {
   "title": "Porcentaje Memoria Usada",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(nodejs_heap_size_used_bytes / nodejs_heap_size_total_bytes)*100",
     "legendFormat": "% Memoria Usada vs Disponible"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"API_exporter\"}[$__rate_interval])*100",
     "legendFormat": "% Uso de CPU"
    }
   ]
  },
  {
   "title": "Latencia Endpoints API",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "Percentil 99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "Percentil 90"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "Percentil 80"
    }
   ]
  }
 ]
}