---
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: 'node_exporter_metrics'
    static_configs:
      - targets: ['192.168.56.2:9100']
  - job_name: 'API_exporter'
    static_configs:
      - targets: ['nodejs:3000']
