ungrouped:
  hosts:
    apache:
      ansible_host: 192.168.56.2
      ansible_user: root
      ansible_password: "{{ lookup('file', pass_folder + 'root.pass') }}"
    nginx:
      ansible_host: 192.168.56.3
      ansible_user: root
      ansible_password: "{{ lookup('file', pass_folder + 'root.pass') }}"

